services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: pre_accounting_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: bozlak
      POSTGRES_PASSWORD: secret
    ports:
      - '5433:5432'
