spring.application.name=on-muhasebe-spring-boot

spring.datasource.url=jdbc:postgresql://localhost:5432/on_muhasebe_db

spring.datasource.username=bozlak

spring.datasource.password=${LOCALHOST_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
#spring.jpa.show-sql=false

spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET_KEY}