-- Test-only schema.
--
-- Until now the integration tests got their schema from Hibernate's
-- spring.jpa.hibernate.ddl-auto=create-drop. Spring Data JDBC does not generate DDL, so
-- the schema is now explicit. It is derived from the entity classes and therefore mirrors
-- what Hibernate used to create.
--
-- No FOREIGN KEY here, and that is not a test concession: this project declares no foreign
-- key constraints on the RDBMS side at all, production included (see README.md). Columns
-- like contacts.user_id are logical references the application keeps valid; the database
-- accepts whatever it is given. That is also why the existing tests can insert rows such
-- as contacts.user_id = 12 with no matching users row. Adding constraints here would make
-- this file stricter than the database it stands in for - so if you are tempted, fix the
-- production DDL first.
--
-- This project is DB-First, so the production database - not this file - is the source of
-- truth. Replace this with a dump of the real schema when convenient:
--     pg_dump --schema-only --no-owner --no-privileges on_muhasebe_db > src/test/resources/schema.sql
-- Numeric columns are declared without precision/scale here for the same reason: the real
-- definitions live in the production DDL.

CREATE TABLE IF NOT EXISTS users (
    user_id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             varchar(255) NOT NULL UNIQUE,
    hashed_password      varchar(255) NOT NULL,
    email                varchar(255) NOT NULL,
    is_active            boolean      NOT NULL,
    is_admin             boolean      NOT NULL,
    created_at           date         NOT NULL,
    who_created_admin_id smallint     NOT NULL,
    extra_information    varchar(255)
);

CREATE TABLE IF NOT EXISTS admins (
    admin_id             smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              integer  NOT NULL UNIQUE,
    is_active            boolean  NOT NULL,
    who_created_admin_id smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    account_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer      NOT NULL,
    account_name    varchar(255) NOT NULL,
    created_at      date         NOT NULL,
    is_cash_account boolean      NOT NULL,
    amount          numeric,
    is_active       boolean      NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_types (
    contact_type_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_type_name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
    contact_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           integer      NOT NULL,
    contact_name      varchar(255) NOT NULL,
    extra_information varchar(255),
    contact_type_id   smallint     NOT NULL,
    phone_number      varchar(255),
    is_active         boolean      NOT NULL
);

CREATE TABLE IF NOT EXISTS product_or_services (
    product_or_service_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 integer      NOT NULL,
    product_or_service_code bigint       NOT NULL,
    product_or_service_name varchar(255) NOT NULL,
    created_at              date         NOT NULL,
    did_delete              boolean      NOT NULL,
    sale_unit_price         numeric,
    purchase_unit_price     numeric,
    inventory               bigint,
    extra_information       varchar(255)
);

CREATE TABLE IF NOT EXISTS user_himself_activities (
    user_himself_activity_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  integer      NOT NULL,
    activity_type_name       varchar(255) NOT NULL,
    created_at               date         NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_activities_about_user (
    admin_activity_about_user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id                     smallint     NOT NULL,
    admin_activity_type          varchar(255) NOT NULL,
    user_id                      integer      NOT NULL,
    created_at                   timestamp    NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_activities_about_contact_type_created_or_deleted (
    admin_activity_about_contact_type_created_or_deleted_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id                                                smallint NOT NULL,
    is_activity_create                                      boolean  NOT NULL,
    contact_type_id                                         smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS user_contact_activities_created_or_deleted (
    user_contact_activity_created_or_deleted_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id                                  bigint  NOT NULL,
    is_activity_create                          boolean NOT NULL,
    which_day                                   date    NOT NULL
);

CREATE TABLE IF NOT EXISTS product_or_service_create_or_delete_activities (
    product_or_service_create_or_delete_activity_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_activity_create                              boolean NOT NULL,
    product_or_service_id                           bigint  NOT NULL,
    created_at                                      date    NOT NULL
);

CREATE TABLE IF NOT EXISTS user_account_create_or_delete_activities (
    user_account_activity_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_activity_create       boolean NOT NULL,
    account_id               bigint  NOT NULL,
    created_at               date    NOT NULL
);
